name: budget_app_starting
description: A new Flutter project.


publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.5.4 <5.0.0'
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  logger: ^2.6.0
  cloud_firestore: ^5.6.11
  firebase_auth: ^5.6.2
  firebase_core: ^3.15.1
  flutter_hooks: ^0.21.2
  hooks_riverpod: ^2.6.1
  google_fonts: ^6.2.1
  google_sign_in: ^7.1.0
  sign_button: ^2.0.6
  url_strategy: ^0.3.0
  url_launcher: ^6.3.1
  flutter_svg: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0



flutter:


  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

