platform :ios, '13.0'

# Disable CocoaPods analytics in CI
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

install! 'cocoapods', deterministic_uuids: false

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  flutter_install_all_ios_pods(File.dirname(File.realpath(__FILE__)))
end

post_install do |installer|
  installer.pods_project.targets.each do |t|
    t.build_configurations.each do |c|
      c.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
    end
  end
end
